// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_5oMAYbZnHxnc6B1RsQxGXkLcINZMy3A',
    appId: '1:213919017926:web:8309d63f0694c1582920c7',
    messagingSenderId: '213919017926',
    projectId: 'fitness-tracker-bitcube',
    authDomain: 'fitness-tracker-bitcube.firebaseapp.com',
    storageBucket: 'fitness-tracker-bitcube.firebasestorage.app',
    measurementId: 'G-EGN22W3XE1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS9Ju5ooYepkhwgbbT3a2Ei9aZEPOujcw',
    appId: '1:213919017926:android:6d0b29dda6dba7462920c7',
    messagingSenderId: '213919017926',
    projectId: 'fitness-tracker-bitcube',
    storageBucket: 'fitness-tracker-bitcube.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHe2wiYNp-75rynci_UB0hCJ-dJydI2gk',
    appId: '1:213919017926:ios:33b945e18580f1de2920c7',
    messagingSenderId: '213919017926',
    projectId: 'fitness-tracker-bitcube',
    storageBucket: 'fitness-tracker-bitcube.firebasestorage.app',
    iosBundleId: 'com.example.fitnessTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHe2wiYNp-75rynci_UB0hCJ-dJydI2gk',
    appId: '1:213919017926:ios:33b945e18580f1de2920c7',
    messagingSenderId: '213919017926',
    projectId: 'fitness-tracker-bitcube',
    storageBucket: 'fitness-tracker-bitcube.firebasestorage.app',
    iosBundleId: 'com.example.fitnessTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_5oMAYbZnHxnc6B1RsQxGXkLcINZMy3A',
    appId: '1:213919017926:web:37d33bf79e60a67d2920c7',
    messagingSenderId: '213919017926',
    projectId: 'fitness-tracker-bitcube',
    authDomain: 'fitness-tracker-bitcube.firebaseapp.com',
    storageBucket: 'fitness-tracker-bitcube.firebasestorage.app',
    measurementId: 'G-0HWB8SFDSC',
  );
}
